# Generated by Django 3.2 on 2021-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='txn_details',
            name='tour_ID',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
